# Generated by Django 2.2.6 on 2021-08-15 02:38

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo_vaga", models.CharField(max_length=20)),
                ("ingredientes", models.TextField()),
                ("modo_preparo", models.TextField()),
                ("tempo_preparo", models.IntegerField()),
                ("rendimento", models.CharField(max_length=100)),
                ("categoria", models.CharField(max_length=50)),
                (
                    "date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
    ]
