# Generated by Django 2.2.6 on 2021-09-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0007_auto_20210921_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='localizacao',
            field=models.CharField(max_length=248),
        ),
    ]
