# Generated by Django 2.2.6 on 2021-09-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0010_auto_20210922_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='competencia',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='curso',
        ),
        migrations.AddField(
            model_name='receita',
            name='salario',
            field=models.CharField(default='', max_length=248),
            preserve_default=False,
        ),
    ]
