# Generated by Django 2.2.6 on 2021-09-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0011_auto_20210928_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='salario',
            field=models.TextField(),
        ),
    ]
